---
title: "southcaucasus"
author: "Daniel Shapiro"
date: "7/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(scipen = 999)
library(tidyverse)
library(readr)
library(readxl)
```

# Turnover

```{r}
turnover <- read_xlsx("raw-data/Trade Turnover.xlsx")
turnover <- turnover %>%
  mutate(`Imports + Exports (Millions USD)` = (`Imports + Exports (Millions USD)`)/1000)
```

```{r}
ggplot(turnover, aes(x = Year, y = `Imports + Exports (Millions USD)`, color = Country)) +
  geom_line() +
  labs(title = "Total Trade with China (Imports + Exports), 2005-2019",
       subtitle = "Data from World Bank")

ggsave("turnover.png")
```

# Total investment

```{r}
inflow <- read_xlsx("raw-data/Total Inflow.xlsx")
```

```{r}
ggplot(inflow, aes(x = Year, y = Amount, color = Country)) +
  geom_point() +
  geom_line() +
  labs(title = "Total FDI Inflow, 2013-2019",
       subtitle = "Data from UNCTAD",
       caption = "Data can be found at https://unctad.org/en/PublicationsLibrary/wir2019_en.pdf.",
       y = "Amount in Millions USD")
```

# Chinese FDI Position

```{r}
chnpos <- read_xlsx("raw-data/china.xlsx")
chnpos <- chnpos[-24, ]
```

```{r}
ggplot(chnpos[!is.na(chnpos$Amount),], aes(x = Year, y = Amount, color = Country)) +
  geom_point() +
  geom_line() +
  labs(title = "Chinese FDI Position in South Caucasus countries",
       subtitle = "Data from IMF",
       y = "Amount in Millions USD",
       caption = "Data can be found at https://data.imf.org/regular.aspx?key=61227424.")
ggsave("fdistock.png")
```

# Georgia FDI Inflow

```{r}
georgia <- read_xlsx("raw-data/georgia.xlsx")
```

```{r}
ggplot(georgia, aes(x = Year, y = Amount)) +
  geom_line() +
  geom_point()
```

